apiVersion: velero.io/v1
kind: Restore
metadata:
  name: hasan-oadp-demo-2-restore
  namespace: openshift-adp
spec:
  backupName: hasan-oadp-demo-2
  includeClusterResources: true
  existingResourcePolicy: update
  restorePVs: true
  restoreStatus:
    includedResources:
    - apis.apiconnect.ibm.com
    - products.apiconnect.ibm.com
    - integrationkeycloakclients.keycloak.integration.ibm.com
    - integrationkeycloakusers.keycloak.integration.ibm.com
  hooks: {}
  includedNamespaces:
  - '*'
  itemOperationTimeout: 1h0m0s
  orLabelSelectors:
  - matchExpressions:
    - key: backup.integration.ibm.com/component
      operator: In
      values:
      - catalogsource
      - operatorgroup
      - subscription
      - assetrepository
      - platformnavigator
      - integrationassembly
      - messagingserver
      - messagingqueue
      - messagingchannel
      - messaginguser
      - validatingadmissionpolicy
      - validatingadmissionpolicybinding
      - commonservice
      - secret
      - configmap
      - namespace
  - matchExpressions:
    - key: backup.apiconnect.ibm.com/component
      operator: In
      values:
      - catalogsource
      - operatorgroup
      - subscription
      - api
      - product
      - apiconnectcluster
      - portalcluster
      - analyticscluster
      - managementcluster
      - secret
      - configmap
  - matchExpressions:
    - key: backup.datapower.ibm.com/component
      operator: In
      values:
      - catalogsource 
      - operatorgroup
      - subscription
      - datapowerservice
      - secret
      - configmap
  - matchExpressions:
    - key: backup.appconnect.ibm.com/component
      operator: In
      values:
      - catalogsource
      - operatorgroup
      - subscription
      - configuration
      - dashboard
      - designerauthoring
      - integrationruntime
      - integrationserver
      - switchserver
      - secret
      - configmap
  - matchExpressions:
    - key: backup.mq.ibm.com/component
      operator: In
      values:
      - catalogsource
      - operatorgroup
      - subscription
      - queuemanager
      - secret
      - configmap
  - matchExpressions:
    - key: backup.eventstreams.ibm.com/component
      operator: In
      values:
      - catalogsource
      - operatorgroup
      - subscription
      - eventstreams
      - kafkaconnect
      - kafkatopic
      - kafkauser
      - kafkabridge
      - kafkaconnector
      - kafkarebalance
      - secret
      - configmap
  - matchExpressions:
    - key: foundationservices.cloudpak.ibm.com
      operator: In
      values:
        - keycloak